name: CADR4 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Fossil
      run: sudo apt-get install -y fossil

    - name: Install GHDL
      run: sudo apt-get install -y ghdl

    - name: Clone hdlmake.mk
      run: fossil clone https://tumbleweed.nu/r/hdlmake.mk ~/hdlmake.mk.fossil

    - name: mkdir ~/hdlmake.mk
      run: mkdir ~/hdlmake.mk

    - name: Open hdlmake.mk
      run: fossil open ~/hdlmake.mk.fossil --workdir ~/hdlmake.mk
    
    - name: Run check
      run: make
